config/routes.rb
Rails.application.routes.draw do


  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
  devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}

  root to: 'homes#top'
  get 'about' => 'homes#about'
  get 'customer/edit' => 'customers#edit'
  patch 'customer/' => 'customers#update', as: 'update_customer'
  get 'customer' => 'customers#show'
  get 'customer/unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
  patch 'customer/withdraw' => 'customers#withdraw', as: 'withdraw_customer'
  put 'customer/withdraw' => 'customers#withdraw'
  post 'orders/confirm' => 'orders#confirm'
  get 'orders/confirms' => 'orders#confirms'
  get 'orders/complete' => 'orders#complete'


  resources :addresses, only: [:index, :edit, :create, :update, :destroy]

  resources :items, only: [:index, :show]
  resources :cart_items, only: [:index, :create, :destroy, :update] do
    collection do
      delete 'destroy_all'
    end
  end
  resources :orders, only: [:index, :create, :destroy, :update, :new, :show]


  namespace :admin do
    root to: "homes#top"
    get '/index/:id' => 'homes#index'
    resources :items, only: [:new, :create, :show, :index, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    post 'order_details/:id' => 'orders#show'


   end
  end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :addresses, dependent: :destroy
  has_many :cart_items
  has_many :orders

  # def active_for_authentication?
  #   super && (self.is_deleted == false)
  # end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  #before_action :authenticate_admin!

  def index
  	@customers = Customer.all
  end

	def show
	@customer = Customer.find(params[:id])
	end

	def edit
	@customer = Customer.find(params[:id])
	end

	def update
	@customer = Customer.find(params[:id])
		if @customer.update(customer_params)
		   flash[:success] = "変更完了"
		   redirect_to admin_customer_path
		else
			render "index"
		end
	end

	private
	def customer_params
	  params.require(:customer).permit(:first_name,:last_name,:first_name_kana,:last_name_kana,:post_code,:address,:phone_number,:email,:is_deleted)
	end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  def after_sign_up_path_for(resource)
    customer_path
  end
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
   #before_action :configure_sign_in_params, only: [:create]
  before_action :reject_customer, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected
  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email].downcase)
    if @customer
      if ((@customer.valid_password?(params[:customer][:password])) && (@customer.active_for_authentication? == false))
        redirect_to new_customer_session_path
      end
    end
  end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # ends
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def show
    @customer = Customer.find(current_customer.id)
  end

  def edit
    @customer = Customer.find(current_customer.id)
  end

  def update
    @customer = Customer.find(current_customer.id)
    @customer.update(customer_params)
    redirect_to
  end

  def unsubscribe
    @customer = Customer.find(current_customer.id)
  end


  def withdraw
    @customer = Customer.find(current_customer.id)
    @customer.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :address, :post_code, :phone_number, :email)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/edit.html.erb
<div class="container mt-3 mb-5">
  <h3>会員情報編集</h3>
  <%= form_with model:@customer, :url => {:action => :update}, local:true do |f| %>
    <div class="row pt-4">
      <div class="col-3">名前</div>
      <div class="form-group col-4">
        <%= f.label "(姓)",for: "inputEmail4", class: "form-label" %><br />
        <%= f.text_field :last_name, autofocus: true, placeholder: "令和",class: "form-control" %>
      </div>

      <div class="form-group col-4">
        <%= f.label "(名)" %><br />
        <%= f.text_field :first_name, autofocus: true, placeholder: "道子",class: "form-control" %>
      </div>
    </div>

    <div class="row">
      <div class="col-3">フリガナ</div>
      <div class="form-group col-4">
        <%= f.label "(セイ)" %><br />
        <%= f.text_field :last_name_kana, autofocus: true, placeholder: "レイワ",class: "form-control" %>
      </div>

      <div class="form-group col-4">
        <%= f.label "(メイ)" %><br />
        <%= f.text_field :first_name_kana, autofocus: true, placeholder: "ミチコ",class: "form-control" %>
      </div>
    </div>

    <div class="row">
      <div class="col-3">郵便番号(ハイフンなし)</div>
      <div class="form-group col-4"><%= f.text_field :post_code, autofocus: true, placeholder: "0000000",class: "form-control" %></div>
    </div>

    <div class="row">
      <div class="col-3">住所</div>
      <div class="form-group col-8"><%= f.text_field :address, autofocus: true, placeholder: "東京都渋谷区代々木神園町0-0",class: "form-control" %></div>
    </div>

    <div class="row">
      <div class="col-3">電話番号(ハイフンなし)</div>
      <div class="form-group col-4"><%= f.text_field :phone_number, autofocus: true, placeholder: "00000000000",class: "form-control" %></div>
    </div>

    <div class="row">
      <div class="col-3">メール</div>
      <div class="form-group col-4"><%= f.email_field :email, autofocus: true, placeholder: "sample@example.com",class: "form-control" %></div>
    </div>

    <div class="row">
      <div class="col-md-3 offset-md-3"><%= f.submit "編集内容を保存",class: "btn btn-success" %></div>
      <div class="col-md-3 offset-md-3"><%= link_to "退会する",confirm_unsubscribe_path,class: "btn btn-danger" %></div>
    </div>
<% end %>
</div>

app/views/customers/show.html.erb
<div class="container mt-3 mb-5">
  <h3>マイページ</h3>

  <div class="row pt-4">
    <h5 class="col-2">登録情報</h5> <div class="col-2"><%= link_to "編集する",customer_edit_path, class: "btn btn-success" %></div>
  </div>

  <table class="table table-bordered mt-4">
    <tr>
      <th class="table-active col-2">氏名</th>
      <td class="col-8"><%= @customer.last_name %><%= @customer.first_name %></td>
    </tr>
    <tr>
      <th class="table-active col-2">フリガナ</th>
      <td class="col-8"><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
    </tr>
    <tr>
      <th class="table-active col-2">郵便番号</th>
      <td class="col-8"><%= @customer.post_code %></td>
    </tr>
    <tr>
      <th class="table-active col-2">住所</th>
      <td class="col-8"><%= @customer.address %></td>
    </tr>
    <tr>
      <th class="table-active col-2">電話番号</th>
      <td class="col-8"><%= @customer.phone_number %></td>
    </tr>
    <tr>
      <th class="table-active col-2">メールアドレス</th>
      <td class="col-8"><%= @customer.email %></td>
    </tr>

  </table>

  <div class="row pt-4">
    <h5 class="col-2">配送先</h5>
    <div class="col-2"><%= link_to"一覧を見る", addresses_path,class: "btn btn-primary" %></div>
  </div>
  <div class="row pt-4">
    <h5 class="col-2">注文履歴</h5>
    <div class="col-4"><%= link_to"一覧を見る", orders_path,class: "btn btn-primary" %></div>
  </div>
</div>

app/views/customers/unsubscribe.html.erb
<div class='container mt-3'>
  <div class='row'>
    <div class='px-3 mx-auto text-center'>

      <h2>本当に退会しますか？</h2>
      <div>
        <p>
          退会すると、会員登録情報や</br>
          これまでの購入履歴が閲覧できなくなります。</br>
          退会する場合は、「退会する」をクリックしてください。
        </p>
      </div>
      <div>
        <%= link_to '退会しない', customer_path,class: "btn btn-primary" %>
        <%= link_to "退会する", withdraw_customer_path,class: "btn btn-danger", method: :patch %>
      </div>

    </div>
  </div>
</div>