config/routes.rb
Rails.application.routes.draw do


  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
  devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}

  root to: 'homes#top'
  get 'about' => 'homes#about'
  get 'customer/edit' => 'customers#edit'
  patch 'customer/' => 'customers#update', as: 'update_customer'
  get 'customer' => 'customers#show'
  get 'customer/unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
  patch 'customer/withdraw' => 'customers#withdraw', as: 'withdraw_customer'
  put 'customer/withdraw' => 'customers#withdraw'
  post 'orders/confirm' => 'orders#confirm'
  get 'orders/confirms' => 'orders#confirms'
  get 'orders/complete' => 'orders#complete'


  resources :addresses, only: [:index, :edit, :create, :update, :destroy]

  resources :items, only: [:index, :show]
  resources :cart_items, only: [:index, :create, :destroy, :update] do
    collection do
      delete 'destroy_all'
    end
  end
  resources :orders, only: [:index, :create, :destroy, :update, :new, :show]


  namespace :admin do
    root to: "homes#top"
    get '/index/:id' => 'homes#index'
    resources :items, only: [:new, :create, :show, :index, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    post 'order_details/:id' => 'orders#show'


   end
  end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  validates :amount, presence: true
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :authenticate_customer!

  def index
    # @item = Item.find(params[:id])
    @customer = Customer.find(current_customer.id)
    @cart_item = CartItem.where(customer_id: current_customer.id)
    @cart_items = CartItem.all
    # @subtotal　= cart_item.item.price * cart_item.amount
    # @item =
    # @amount = Item.amount
  end

  def create
    @cart_item = CartItem.new(cart_item_params)
    @cart_item.customer_id = current_customer.id
    # @cart_items = current_user.cart_items.all
    if @cart_item.save
      redirect_to cart_items_path
    else
      # session[:cart_item] = @cart_item.attributes.slice(*cart_item_params.keys)
      redirect_to items_path
    end
  end

  def destroy
    @customer = Customer.find(current_customer.id)
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    redirect_to cart_items_path
  end

  def destroy_all
    CartItem.destroy_all
    redirect_to cart_items_path
  end

  def update
    # @cart_item = CartItem.where(customer_id: current_customer.id)
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(cart_item_params)
    # @cart_item.update(amount: params[:amount].to_i)
    redirect_to cart_items_path
  end


  private

  def cart_item_params
    params.require(:cart_item).permit(:item_id, :amount, :customer_id)
  end

end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/index.html.erb
<div class="container">
 <h3 class="pt-3 ml-5"><span style="background-color:#EEEEEE">ショッピングカート</span></h3>
  <div class="text-right pb-3">
   <%= link_to "カートを空にする", destroy_all_cart_items_path, method: :delete, data: {confirm: "本当に消しますか？"}, class:"btn btn-danger" %>
  </div>
  <div class="row">
   <div class="col-md-12 mx-auto">
    <table class="table table-bordered width=100%">
     <thead class="thead-light">
      <tr>
       <th width="48%">商品名</th>
       <th width="13%">単価</th>
       <th width="13%">数量</th>
       <th width="13%">小計</th>
       <th width="13%"></th>
      </tr>
     </thead>
   </div>
   <% @sum = 0 %>
   <% @cart_item.each do |cart_item| %>
   <tr>
    <td><%= attachment_image_tag cart_item.item, :image, width: '10%', height: 'auto' %>
     <%= cart_item.item.name %></td>
    <td><%= converting_to_jpy(cart_item.item.add_tax_price) %></td>
    <td>
      <%= form_with model: cart_item, url: cart_item_path(cart_item), method: :patch, local: true do |f| %>
      <%#= f.hidden_field :item_id, value: @item.id %>
       <%= f.select :amount, [[1], [2], [3], [4],[5]] %>
       <%= f.submit '変更',class:"btn btn-success btn-sm" %>
       <% end %>
     <%#= link_to "変更", cart_item.amount(@cart_item), method: :patch, class:"btn btn-success" %>
     </td>
     <td>
      <%= converting_to_jpy(cart_item.item.add_tax_price * cart_item.amount) %>
     <!--ここはsum+=sub_total　と%= sub_total -->
     </td>
     <td><%= link_to "削除する", cart_item_path(cart_item), method: :delete, data: {confirm: "本当に消しますか？"}, class:"btn btn-danger" %></td>
   </tr>
    <% @sum += cart_item.item.add_tax_price * cart_item.amount %>
   <% end %>
  </table>
  <div class="row justify-content-between">
   <div class="col-md-3 mt-8">
    <%= link_to "買い物を続ける", root_path,class:"btn btn-primary" %>
   </div>
   <div class="col-md-5 mt-8">
    <table class="table table-bordered">
     <tr>
      <th>合計金額</th>
      <th>
       <%= converting_to_jpy(@sum) %>
      </th>
     </tr>
    </table>
   </div>
 </div>
 <div class="row">
  <div class="mx-auto" style="width: 200px;">
   <%= link_to "情報入力を続ける", new_order_path,class:"btn btn-success" %>
  </div>
 </div>
</div>