config/routes.rb
Rails.application.routes.draw do


  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
  devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}

  root to: 'homes#top'
  get 'about' => 'homes#about'
  get 'customer/edit' => 'customers#edit'
  patch 'customer/' => 'customers#update', as: 'update_customer'
  get 'customer' => 'customers#show'
  get 'customer/unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
  patch 'customer/withdraw' => 'customers#withdraw', as: 'withdraw_customer'
  put 'customer/withdraw' => 'customers#withdraw'
  post 'orders/confirm' => 'orders#confirm'
  get 'orders/confirms' => 'orders#confirms'
  get 'orders/complete' => 'orders#complete'


  resources :addresses, only: [:index, :edit, :create, :update, :destroy]

  resources :items, only: [:index, :show]
  resources :cart_items, only: [:index, :create, :destroy, :update] do
    collection do
      delete 'destroy_all'
    end
  end
  resources :orders, only: [:index, :create, :destroy, :update, :new, :show]


  namespace :admin do
    root to: "homes#top"
    get '/index/:id' => 'homes#index'
    resources :items, only: [:new, :create, :show, :index, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    post 'order_details/:id' => 'orders#show'


   end
  end

app/views/layouts/_aheader.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <a class="navbar-brand" href="/">NaganoCake<i class="fab fa-java"></i></a>



          <ul class="navbar-nav ml-auto">

            <li class="nav-item">
            <%= link_to '商品一覧', admin_items_path,class: 'nav-link' %>
            </li>
            <li class="nav-item">
            <%= link_to '会員一覧', admin_customers_path,class: 'nav-link' %>
            </li>
            <li class="nav-item">
            <%= link_to '注文履歴一覧', admin_root_path,class: 'nav-link' %>
            </li>
            <li class="nav-item">
            <%= link_to 'ジャンル一覧', admin_genres_path,class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete,class: 'nav-link' %>
            </li>
          </ul>

      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/_footer.html.erb
<footer class="footer mt-4 py-2 bg-light fixed-bottom">
  <div class='container'>
    <p class="text-center"><i class="fab fa-jenkins"></i></p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <a class="navbar-brand" href="/">NaganoCake<i class="fab fa-java"></i></a>

        <% if customer_signed_in? %>
          <p class="wf-hannari offset-md-2">ようこそ、<%= @customer.last_name %>さん！</p>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
            <%= link_to 'マイページ', customer_path,class: 'nav-link' %>
            </li>
            <li class="nav-item">
            <%= link_to '商品一覧', items_path,class: 'nav-link' %>
            </li>
            <li class="nav-item">
            <%= link_to 'カート', cart_items_path,class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_customer_session_path, method: :delete,class: 'nav-link' %>
            </li>
          </ul>
        <% else %>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
            <%= link_to 'About', about_path,class: 'nav-link' %>
            </li>
            <li class="nav-item">
            <%= link_to '商品一覧', items_path,class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "新規登録", new_customer_registration_path,class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_customer_session_path,class: 'nav-link' %>
            </li>
          </ul>
        <% end %>

      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!--link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script-->


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Caveat" rel="stylesheet">
    <link href="https://fonts.googleapis.com/earlyaccess/hannari.css" rel="stylesheet">
  </head>

  <body>
    <% if admin_signed_in? %>
      <%= render 'layouts/aheader', admin: @admin %>
    <% else %>
      <%= render 'layouts/header', customer: @customer %>
    <% end %>

    <%= yield %>


  </div>
    <%= render 'layouts/footer' %>
  </div>
  </body>

</html>